on:
  push:
    branches:
      - customdev

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: react.customdev.solutions
          username: customdev@react.customdev.solutions
          password: ${{ secrets.FTP_PASSWORD_CUSTOMDEV }}
          protocol: ftp
          port: 21
          local-dir: ./dist/
          server-dir: /shopdit-business/